name: NixOS Package Building

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-stregsystemet:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1

            - uses: nixbuild/nix-quick-install-action@v27
            - uses: nix-community/cache-nix-action@v5

            - name: build-stregsystemet
              run: nix build .#stregsystemet
